### PR TITLE
Replace atty with is_terminal

### LINKED ISSUE #9: `atty` is potentially unsound, not very alive and should be replaced with `is-terminal`
Some links explaining the problem

- https://github.com/softprops/atty/pull/51
- https://github.com/clap-rs/clap/pull/4249#discussion_r1029107456
- https://github.com/rustsec/advisory-db/issues/1457

I can prepare a pull request if you like

### PR DESCRIPTION
**Pull request by pacak**
Fixes https://github.com/zkat/supports-color/issues/9

### CODE REVIEW

**Comment by pacak** [comment]
Any thoughts?

**Comment by zkat** [comment]
Oh sorry, I don't know how this fell off my list.

**Review by zkat — APPROVED** [review]
This LGTM. It's unfortunate that it has to be a semver-major change, but that's my own fault for having re-exported atty types like that. Thank you!

**Comment by Porges** [comment]
I would argue that since the API is breaking anyway the exposed function should accept any `IsTerminal`, which makes the `on` function more general and flexible.

**Comment by pacak** [comment]
> I would argue that since the API is breaking anyway the exposed function should accept any IsTerminal, which makes the on function more general and flexible.

Too late for that I'm afraid. Using `IsTerminal` required more changes to cached version of supports color request. Doable, but more complex and it would couple `supports-color` to `is_terminal`.

**Comment by Porges** [comment]
> > I would argue that since the API is breaking anyway the exposed function should accept any IsTerminal, which makes the on function more general and flexible.
> 
> Too late for that I'm afraid. Using `IsTerminal` required more changes to cached version of supports color request. Doable, but more complex and it would couple `supports-color` to `is_terminal`.

Maybe a feature-gated alternative function would be useful?

**Comment by zkat** [comment]
I definitely feel a bit weird that all the other `supports-*` crates would end up using `IsTerminal`, but `supports-color` wouldn't. I'm trying to figure out what would be best. I don't think it's inherently bad to couple to `is-terminal` if it's going to be a more permanent fixture in the cargo ecosystem, tbh.

**Comment by Porges** [comment]
> I definitely feel a bit weird that all the other `supports-*` crates would end up using `IsTerminal`, but `supports-color` wouldn't. I'm trying to figure out what would be best. I don't think it's inherently bad to couple to `is-terminal` if it's going to be a more permanent fixture in the cargo ecosystem, tbh.

It will at some point be replaced by [`std::io::IsTerminal`](https://doc.rust-lang.org/nightly/std/io/trait.IsTerminal.html#), so maybe the best thing to do is to expose the `Stream`-enum API for now and then switch to the trait when it is no longer unstable.

**Pull request merged**
