### PR TITLE
Add CLICOLOR support

### LINKED ISSUE #3: Add support for CLICOLOR and CLICOLOR_FORCE
Based on https://github.com/zkat/miette/issues/74;

Support CLICOLOR and CLICOLOR_FORCE. See https://bixense.com/clicolors/ for details

### PR DESCRIPTION
**Pull request by dswij**
Closes #3

### CODE REVIEW

**Review by zkat — APPROVED** [review]

**Comment by zkat** [comment]
Thank you! This looks great!

**Comment by zkat** [comment]
This has been released as part of `supports-color@1.2.0` so you should be able to `cargo update` and have it get picked up by miette :)

**Comment by dswij** [comment]
Oh, whoops. Unit test is failing on GH action. Will look into it soon when time allows

**Comment by zkat** [comment]
wait what?

**Pull request merged**
